package py.una.pol.ia.mochila.gui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import py.una.pol.ia.mochila.Item;
import py.una.pol.ia.mochila.MochilaBacktracking;
import py.una.pol.ia.mochila.MochilaUtil;
import py.una.pol.ia.mochila.MochilaVegas;
import py.una.pol.ia.mochila.MochilaVoraz;

/**
 * @author Claudia Valenzuela
 * @version 1.0
 */
public class Mochila extends javax.swing.JFrame {

    /**
     * Creates new form Mochila
     */
    public Mochila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPesoMaximo = new javax.swing.JLabel();
        lblNroElementos = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtPesoMaximo = new javax.swing.JFormattedTextField();
        txtNroElementos = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PSR - Problema de la Mochila");

        lblPesoMaximo.setText("Peso Máximo:");

        lblNroElementos.setText("Número de Elementos:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtPesoMaximo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###"))));
        txtPesoMaximo.setText("300");

        txtNroElementos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###"))));
        txtNroElementos.setText("100");
        txtNroElementos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Algoritmo", "Tiempo(ms)", "Nodos Expandidos", "Peso Obtenido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableResult.setName("Resultados"); // NOI18N
        jScrollPane1.setViewportView(tableResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNroElementos)
                            .addComponent(lblPesoMaximo))
                        .addGap(18, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesoMaximo, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtNroElementos))))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPesoMaximo)
                    .addComponent(txtPesoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNroElementos)
                    .addComponent(txtNroElementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        int numeroElementos = 0;
        int pesoMaximo = 0;
        long tiVoraz = 0;
        long tfVoraz = 0;
        long tiVegas = 0;
        long tfVegas = 0;
        long tiBack = 0;
        long tfBack = 0;
        long tiempoVoraz;
        long tiempoVegas;
        long tiempoBack;
        numeroElementos = Integer.parseInt(txtNroElementos.getText());
        pesoMaximo = Integer.parseInt(txtPesoMaximo.getText());
        List<Item> almacen = MochilaUtil.generarElementos(numeroElementos);

        //Algoritmo Voraz
        MochilaVoraz mochilaVoraz = new MochilaVoraz(almacen, pesoMaximo);
        tiVoraz = System.currentTimeMillis();
        mochilaVoraz.resolverProblema();
        tfVoraz = System.currentTimeMillis();
        MochilaUtil.mostrarMochila(mochilaVoraz);
        tiempoVoraz = tfVoraz - tiVoraz;
        System.out.println("Tiempo ejecución Voraz: " + tiempoVoraz);

        //Algoritmo Vegas
        MochilaVegas mochilaVega = new MochilaVegas(almacen, pesoMaximo);
        tiVegas = System.currentTimeMillis();
        mochilaVega.resolverProblema();
        tfVegas = System.currentTimeMillis();
        MochilaUtil.mostrarMochila(mochilaVega);
        tiempoVegas = tfVegas - tiVegas;
        System.out.println("Tiempo ejecución Vegas: " + tiempoVegas);
        

        //Algoritmo Backtracking
//        MochilaBacktracking mochilaBack = new MochilaBacktracking(almacen, pesoMaximo);
//        tiBack=System.currentTimeMillis();
//        mochilaBack.resolverProblema();
//        tfBack=System.currentTimeMillis();
//        MochilaUtil.mostrarMochila(mochilaBack);
//        tiempoBack=tfBack-tiBack;
//        System.out.println("Tiempo ejecución Backtracking: "+tiempoBack);
//       

        // datos para la tabla
        DefaultTableModel model = (DefaultTableModel) tableResult.getModel();

        Object[][] rows = new Object[][]{
            //{"BackTracking", new Long(tiempoBack), 0, 0},
            {"Las Vegas", new Long(tiempoVegas), mochilaVega.getNodosExp(), mochilaVega.getPesoMochila()},
            {"Voraz", new Long(tiempoVoraz), mochilaVoraz.getNodosExpandidos(), mochilaVoraz.getPesoMochila()}};

        for (Object[] row : rows) {
            model.addRow(row);
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mochila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mochila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mochila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mochila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mochila().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNroElementos;
    private javax.swing.JLabel lblPesoMaximo;
    private javax.swing.JTable tableResult;
    private javax.swing.JFormattedTextField txtNroElementos;
    private javax.swing.JFormattedTextField txtPesoMaximo;
    // End of variables declaration//GEN-END:variables
}
